name: project1
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.1
  table_calendar: ^3.0.9
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  get:
  http:
  shared_preferences: ^2.2.1
  provider: ^6.0.5
  flutter_lints: ^2.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/
